{
 "title": "Test-Cluster-Performance-Read",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": "show databases" }
  ]
 },
 "panels": [
  {
   "title": "Query QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(qr)/10 as \"QPS\" FROM (SELECT sum(queryReq) AS \"qr\" FROM $database..\"httpd\" WHERE $timeFilter GROUP BY time(10s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DML Query QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"count\")/10 as \"DML\", difference(\"qr\")/10 as \"Query\" FROM (SELECT sum(exec_run_time_count) as \"count\", sum(queryReq) AS \"qr\" FROM $database..\"httpd\", $database..\"executor\" WHERE app='ts-sql' AND $timeFilter GROUP BY time(10s) FILL(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"duration\")/difference(\"qr\")/1000000 as \"latency\" FROM (SELECT sum(queryReqDurationNs) AS \"duration\", sum(queryReq) AS \"qr\" FROM $database..\"httpd\" WHERE $timeFilter GROUP BY time(2m))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DML Query Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"runtime\")/difference(\"count\")/1000000 AS \"DML\", difference(\"duration\")/difference(\"qr\")/1000000 AS \"Query\" FROM (SELECT sum(exec_run_time_sum) AS \"runtime\", sum(exec_run_time_count) AS \"count\", sum(queryReqDurationNs) AS \"duration\", sum(queryReq) AS \"qr\" FROM $database..\"httpd\", $database..\"executor\" WHERE app='ts-sql' AND $timeFilter GROUP BY time(10s) FILL(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"AbortCount\") AS \"Abort\", difference(\"FailedCount\") AS \"Failed\", difference(\"TimeoutCount\") AS \"Timeout\" FROM (SELECT sum(exec_abort_count) as \"AbortCount\", sum(exec_failed_count) as \"FailedCount\", sum(exec_timeout_count) as \"TimeoutCount\" FROM $database..\"executor\" WHERE $timeFilter GROUP BY time(10s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Store DML Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"duration\")/difference(\"count\")/1000000 as \"latency\" FROM (SELECT sum(exec_run_time_sum) AS \"duration\", sum(exec_run_time_count) AS \"count\" FROM $database..\"executor\" WHERE app='ts-store' AND $timeFilter GROUP BY time(10s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"hostname\" as \"host\", top(\"last_count\", 60) as \"distribution\" FROM (SELECT last(count) as \"last_count\" FROM (SELECT last(queryReq)-first(queryReq) AS \"count\" FROM $database..\"httpd\" WHERE $timeFilter GROUP BY \"hostname\") GROUP BY \"hostname\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DML Query Distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"hostname\" as \"host\", top(\"last_count\",60) as \"distribution\" FROM (SELECT last(\"count\") as last_count FROM (SELECT max(exec_run_time_count)-min(exec_run_time_count) as count FROM $database..\"executor\" WHERE app='ts-sql' AND $timeFilter GROUP BY \"hostname\") GROUP BY \"hostname\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Store Query Distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"hostname\" as \"host\", top(\"last_count\",60) as \"distribution\" FROM (SELECT last(\"count\") as last_count FROM (SELECT max(exec_run_time_count)-min(exec_run_time_count) as count FROM $database..\"executor\" WHERE app='ts-store' AND $timeFilter GROUP BY \"hostname\") GROUP BY \"hostname\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sql Scan RPQ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(rows)/difference(count) FROM (SELECT sum(source_rows_sum) as rows, sum(exec_run_time_count) as count FROM $database..\"executor\" WHERE app='ts-sql' AND $timeFilter GROUP BY time(10s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Store Scan RPQ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(rows)/difference(count) FROM (SELECT sum(source_rows_sum) as rows, sum(exec_run_time_count) as count FROM $database..\"executor\" WHERE app='ts-store' AND $timeFilter GROUP BY time(10s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sql Calc RPQ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(rows)/difference(count) FROM (SELECT sum(sink_rows_sum) as rows, sum(exec_run_time_count) as count FROM $database..\"executor\" WHERE app='ts-sql' AND $timeFilter GROUP BY time(10s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Store Calc RPQ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(rows)/difference(count) FROM (SELECT sum(sink_rows_sum) as rows, sum(exec_run_time_count) as count FROM $database..\"executor\" WHERE app='ts-store' AND $timeFilter GROUP BY time(10s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ActiveQueryNumTotalMean",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"queryReqActive\") AS \"queryReqActive\" FROM $database..\"httpd\" WHERE $timeFilter GROUP BY time($__interval) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "activeQueryNum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"queryReqActive\") AS \"queryReqActive\" FROM $database..\"httpd\" WHERE $timeFilter GROUP BY time($__interval),\"hostname\" FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CpuUsageTotalMean(%) ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"CpuUsage\") AS \"CPU\" FROM $database..\"system\" WHERE $timeFilter GROUP BY time($__interval) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MemUsageTotalMean(100%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"MemUsage\") as \"Mem\" FROM $database..\"system\" WHERE $timeFilter GROUP BY time(1m) FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cpuUsage(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "query": "SELECT mean(\"CpuUsage\")/64 FROM $database..\"runtime\" WHERE $timeFilter  and app = 'ts-store' GROUP BY time($__interval),\"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "CpuUsage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "memUsage(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"MemUsage\") as \"Mem\" FROM $database..\"system\" WHERE $timeFilter GROUP BY time(1m), \"host\" FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "sql-node-gc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"NumGC\") AS \"NumGC\" FROM $database..\"runtime\" WHERE $timeFilter  AND \"hostname\" =~ /8086/ GROUP BY time($__interval),\"hostname\" FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "store-node-gc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"NumGC\") AS \"NumGC\" FROM $database..\"runtime\" WHERE $timeFilter  AND \"hostname\" =~ /8401/ GROUP BY time($__interval),\"hostname\" FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "sql-node-goroutine",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"NumGoroutine\") AS \"NumGoroutine\" FROM $database..\"runtime\" WHERE $timeFilter AND \"hostname\" =~ /8086/ GROUP BY time($__interval), \"hostname\" FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "store-node-goroutine",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"NumGoroutine\") AS \"NumGoroutine\" FROM $database..\"runtime\" WHERE $timeFilter AND \"hostname\" =~ /8401/ GROUP BY time($__interval), \"hostname\" FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "conn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"connTotal\") AS \"mean_connTotal\" FROM $database..\"spdy\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\" FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "查询端到端时延（ms）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"duration\")/difference(\"qr\")/1000000 as \"latency\" FROM (SELECT queryReqDurationNs AS \"duration\",queryReq AS \"qr\" FROM $database..\"httpd\" WHERE $timeFilter GROUP BY  hostname) group by hostname",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}