{
 "title": "Test-Cluster-Process-Restarted",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": "show databases" }
  ]
 },
 "panels": [
  {
   "title": "Store进程是否重启 (pid变化)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col-$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"StorePid\") as \"StorePid\" FROM $database..\"system\" WHERE $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sql进程是否重启 (pid变化)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col-$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"SqlPid\") as \"SqlPid\" FROM $database..\"system\" WHERE $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meta进程是否重启 (pid变化)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col-$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"MetaPid\") as \"MetaPid\" FROM $database..\"system\" WHERE $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Store最近重启时间",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col-$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"pid\") as \"count_pid\" from (SELECT difference(\"StorePid\") as \"pid\" FROM $database..\"system\" WHERE $timeFilter GROUP BY \"host\") where pid != 0 GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sql最近重启时间",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col-$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"pid\") as \"count_pid\" from (SELECT difference(\"SqlPid\") as \"pid\" FROM $database..\"system\" WHERE $timeFilter GROUP BY \"host\") where pid != 0 GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meta最近重启时间",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col-$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"pid\") as \"count_pid\" from (SELECT difference(\"MetaPid\") as \"pid\" FROM $database..\"system\" WHERE $timeFilter GROUP BY \"host\") where pid != 0 GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Store重启次数",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Store_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"pid\") as \"count_pid\" from (SELECT difference(\"StorePid\") as \"pid\" FROM $database..\"system\" WHERE $timeFilter GROUP BY \"host\") where pid != 0 GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sql重启次数",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Sql_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"pid\") as \"count_pid\" from (SELECT difference(\"SqlPid\") as \"pid\" FROM $database..\"system\" WHERE $timeFilter GROUP BY \"host\") where pid != 0 GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meta重启次数",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Meta_$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"pid\") as \"count_pid\" from (SELECT difference(\"MetaPid\") as \"pid\" FROM $database..\"system\" WHERE $timeFilter GROUP BY \"host\") where pid != 0 GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}